name: Deploy to Azure

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify JAR file was created
        run: |
          echo "Verificando creación del JAR..."
          if [ ! -d "target" ]; then
            echo "ERROR: No existe directorio target/"
            exit 1
          fi
          
          JAR_FILES=$(find target -name "*.jar" -type f)
          if [ -z "$JAR_FILES" ]; then
            echo " ERROR: No se encontraron archivos JAR en target/"
            echo " Contenido de target/:"
            ls -la target/
            exit 1
          fi
          
          echo "JARs encontrados:"
          echo "$JAR_FILES"
          echo "Tamaño de los JARs:"
          ls -lh target/*.jar

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'masterchef-karol-2025'
          package: './target/*.jar'